repos:
  - repo: https://github.com/FlamingTempura/bibtex-tidy/
    rev: v1.11.0
    hooks:
    - id: bibtex-tidy
      args:
      - '--quiet'
      - '--strip-enclosing-braces'
      - '--curly'
      - '--numeric'
      - '--space=2'
      - '--align=14'
      - '--duplicates=citation'
      - '--merge=first'
      - '--escape'
      - '--drop-all-caps'
      - '--no-trailing-commas'
      - '--encode-urls'
      - '--no-backup'
      - '--sort=year,date,name,title'
      - '--sort-fields=title,shorttitle,author,year,month,day,journal,booktitle,location,on,publisher,address,series,volume,number,pages,doi,isbn,issn,url,urldate,copyright,category,note,metadata'
      - '--omit=abstract,address,on,doi,isbn,issn,month_numeric,urldate,copyright,category,metadata,pdf,added-at,biburl,file,groups,interhash,intrahas,_isbn,keywords,timestamp,username'
